### ISSUE TITLE
Find patient examples

### ISSUE THREAD

**Issue by NickMateus11** [McMasterAI/POST_study_Project#11]
- Find patients with clear upward/downward trends in _ices_amountdose_ and/or _ices_opioidbase_, _ices_opioid3_, _ices_opioid6_, _ices_opioid9_, _ices_opioid12_

Groups:
- Edward, Emily, Leiah (A)
- Omar, Aidan (B)

DoD:
-  Find 5 patients with upward/downward trends of _ices_amountdose_ , ices_currdose3, ices_currdose6, ices_currdose9, ices_currdose12 (B)
-  Find 5 patients with upward/downward trends of _ices_opioidbase_, _ices_opioid3_, _ices_opioid6_, _ices_opioid9_, _ices_opioid12_ (A)
- Record the IDs for those patients

**Comment by aidanmathew** [comment]
@ome7o 

Downward Trends:
0,
2795,
2858,

Upward Trend:
2861,
2892,


NoChange:
2830

**Comment by edwardzhuang2001** [comment]
Given in ices_caseid.

Downward trend:
100027,
100029,
100057,
100109,
100169

Upward trend:
100050,

No change:
100040
