### ISSUE TITLE
Determine a patient's success (good/bad) based on data features

### ISSUE THREAD

**Issue by NickMateus11** [McMasterAI/POST_study_Project#15]
- Using the work done by ticket #21, take a patient's data on urine/dosage and compute whether or not they have an upward or downward trend
- return a true or false to state that the patient is either successful in their treatment or not
- The quantitative threshold for whether a patient has been successful is going to be up to you.

**Comment by hafezissa** [comment]
Calculated the slopes of urine concentration and dosage. We decided to use Urine Slope as the metric that decides the patients' treatment outcome. If a patient has a slope less than -5 we can consider them as successfully treated, meaning a positive label.
