### ISSUE TITLE
Determine sparsity of the data set features

### ISSUE THREAD

**Issue by NickMateus11** [McMasterAI/POST_study_Project#19]
We want to see which data features are full and not sparse. So are there features that have a low number of NULL or N/A? Identify top 30 features.

DoD: Maybe plot or list the 30 features along with how many valid entries there are (non-null).

**Comment by edwardzhuang2001** [comment]
dta_file_converted.csv appears to have lost some data from columns AN-CE on rows 1392 and below

For this ticket, I just assumed that they contained null values
